name: build-action
on: [push]
jobs:
  check-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pip install cmake
      - run: pip install make
      - run: make